name: CI/CD

on:
  # Run on pushes to main or develop
  push:
    branches:
      - main
      - develop
      - feature/*  # This line (if applied) makes sure that ci workflow will run on every branch that starts with feature/...
    tags:
      - "v*"
  # Run on pull requests targeting main
  # Runs when PR is opened not when it is approved!
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Dependencies 
        run: pip install -e ".[dev]"

      - name: Run ruff
        run: ruff check .
  
  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest] # we can also pass windows-latest, etc...
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup python 
        uses: actions/setup-python@v6
        with:
          python-version: ${{matrix.python-version}}
          cache: "pip"

      - name: Install Dependencies 
        run: pip install -e ".[dev]"

      - name: Run tests
        run: pytest --cov=. --cov-report=html

      - name: Upload coverage cov report 
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report-${{matrix.python-version}}
          path: ./htmlcov
          retention-days: 30
  build:
    needs: test 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v6

      - name: Setup Python 
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -e ".[build]" 

      - name: Build Application
        run: python -m build 
      
      - name: Upload dist
        uses: actions/upload-artifact@v7
        with:
          name: package
          path: ./dist
          retention-days: 30
  deploy:
    needs: build
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download package
        uses: actions/download-artifact@v8
        with:
          name: package
          path: ./package
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: ./package/*



# jobs:
#   run-python:
#     strategy:
#       matrix:
#         os: [ubuntu-latest]
#         # cutting this one out for now since it slows down builds but it works
#         # , windows-latest]
#         python-version: ["3.10", "3.11", "3.12"]
#
#     runs-on: ${{matrix.os}}
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#
#       - name: Set up Python 
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{matrix.python-version}}
#
#       - name: Install dependencies
#         run: pip install pytest ruff
#
#       - name: Run ruff
#         run: ruff check .
#
#       - name: Run tests
#         run: pytest
#
#


